//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Floor()
        {
            this.LeasingAgreements = new HashSet<LeasingAgreement>();
            this.MaintenanceRequests = new HashSet<MaintenanceRequest>();
        }
    
        public int FloorID { get; set; }
        public string Rooms { get; set; }
        public int FloorNumber { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> ApartmentID { get; set; }
        public string Status { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeasingAgreement> LeasingAgreements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceRequest> MaintenanceRequests { get; set; }
    }
}
