//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintenanceRequest()
        {
            this.MaintenanceAssignments = new HashSet<MaintenanceAssignment>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int RequestID { get; set; }
        public int ApartmentID { get; set; }
        public Nullable<int> FloorNum { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> TenantID { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Floor Floor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceAssignment> MaintenanceAssignments { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
