//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceAssignment
    {
        public int AssignmentID { get; set; }
        public int RequestID { get; set; }
        public int AssignedStaffID { get; set; }
        public System.DateTime AssignmentDate { get; set; }
        public string CompletionStatus { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual MaintenanceRequest MaintenanceRequest { get; set; }
    }
}
