//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> LeaseID { get; set; }
        public decimal PaymentAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentDesc { get; set; }
        public Nullable<int> MaintenanceID { get; set; }
    
        public virtual LeasingAgreement LeasingAgreement { get; set; }
        public virtual LeasingAgreement LeasingAgreement1 { get; set; }
        public virtual MaintenanceRequest MaintenanceRequest { get; set; }
    }
}
